import {
  Banknote,
  Briefcase,
  Brush,
  Building2,
  Camera,
  Car,
  ChefHat,
  Cpu,
  Flower2,
  Hammer,
  Handshake,
  Heart,
  Home as HomeIcon,
  Landmark,
  Palette,
  Scale,
  Scissors,
  Sparkles,
  Stethoscope,
  Tractor,
  Truck,
  Wrench,
  type LucideIcon,
} from 'lucide-react'

const ICONS: Record<string, LucideIcon> = {
  administrativo: Briefcase,
  vendas: Handshake,
  logistica: Truck,
  ti: Cpu,
  construcao: Hammer,
  saude: Stethoscope,
  educacao: Landmark,
  gastronomia: ChefHat,
  financeiro: Banknote,
  producao: Building2,
  agronegocio: Tractor,
  marketing: Palette,
  hotelaria: HomeIcon,
  pedreiro: Hammer,
  eletricista: Sparkles,
  encanador: Wrench,
  consultor: Handshake,
  auditor: Scale,
  diarista: HomeIcon,
  jardineiro: Flower2,
  pintor: Brush,
  marceneiro: Hammer,
  cabeleireiro: Scissors,
  'personal-trainer': Heart,
  fotografo: Camera,
  'designer-freelancer': Palette,
  'professor-particular': Landmark,
  cuidador: Heart,
  'motorista-particular': Car,
  'tecnico-informatica': Cpu,
}

export function iconForCategory(slug: string | null | undefined): LucideIcon {
  if (!slug) return Briefcase
  return ICONS[slug] ?? Briefcase
}
